language: php
os: linux
dist: trusty
php:
  - 7.3
services:
  - postgresql
before_install:
  - composer self-update
  - npm i npm@latest -g
install:
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - git clone https://github.com/ellllllen/portfolio-migrations.git
  - cd portfolio-migrations && git checkout master && cp .env.travis .env && npm install --production && npm run migrate-travis && cd ../ && rm -rf portfolio-migrations
script:
  - ./vendor/bin/phpunit tests --coverage-clover=coverage.xml
cache:
  directories:
    - vendor
after_success:
  - bash <(curl -s https://codecov.io/bash)
