version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 82:80
    restart: always
    depends_on:
      - php
  php:
    build: .
    restart: always
    volumes:
      - .:/var/www/html
      - ./../portfolio-migrations/databases:/var/www/html/sqlite
